from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
from reportlab.lib import colors
from book.styles import ChapterMarker, add_callout, add_code_block, add_table

def build_part1(styles):
    story = []
    
    PRIMARY = colors.HexColor("#0F172A")
    SECONDARY = colors.HexColor("#1D4ED8")
    
    # =========================================================================
    # PART I TITLE PAGE
    # =========================================================================
    story.append(Spacer(1, 140))
    story.append(Paragraph("PART I", styles['PartNumber']))
    story.append(Paragraph("THE GENESIS & THE PRODUCT PHILOSOPHY", styles['PartTitle']))
    story.append(HRFlowable(width="60%", thickness=2, color=SECONDARY, spaceAfter=14, spaceBefore=6, hAlign='CENTER'))
    story.append(Paragraph("Deconstructing the Modern Attention Crisis, the Psychology of Digital Fatigue, and the Five Sacred Tenets of Quiet Media", styles['PartSubtitle']))
    story.append(PageBreak())

    # =========================================================================
    # CHAPTER 1: THE PROBLEM SPACE
    # =========================================================================
    story.append(ChapterMarker("ch1"))
    story.append(Paragraph("Chapter 1: The Problem Space: Algorithmic Outrage & Digital Pollution", styles['ChapterTitle']))
    story.append(HRFlowable(width="100%", thickness=1, color=SECONDARY, spaceAfter=14, spaceBefore=4))
    
    story.append(Paragraph(
        "To build enduring software, one must first clearly articulate the civilizational failure it seeks to remediate. "
        "Keywords News was not created to add another product to the digital landfill; it was conceived as a defensive sanctuary "
        "against an engineered epidemic of distraction and cognitive fatigue.",
        styles['Body']
    ))
    
    story.append(Paragraph("<b>1.1 The Anatomy of the Attention Economy</b>", styles['H2']))
    story.append(Paragraph(
        "For the first three centuries of print journalism, news organizations operated under a dual mandate: civic responsibility "
        "and commercial viability. Subscriptions funded newsrooms, and while sensationalism certainly existed, the physical constraints "
        "of the print medium created natural boundaries. A newspaper arrived once a day; it possessed finite physical pages; its headlines "
        "had to reflect considered editorial judgment. There was a definitive end to the reading experience: once the final page was turned, "
        "the reader folded the paper and returned to their life, grounded in the realities of their community.",
        styles['Body']
    ))
    story.append(Paragraph(
        "The digital transformation erased these natural physical boundaries. In doing so, it inverted the incentives of media companies. "
        "In a programmatic advertising model, page views, click-through rates, and time-on-screen are the sole metrics of commercial survival. "
        "A thoughtful, 4,000-word analysis of Indian fiscal federalism earns a tiny fraction of the ad revenue generated by a sensationalized, "
        "emotionally volatile headline that triggers 100,000 viral reactions on social media.",
        styles['Body']
    ))
    story.append(Paragraph(
        "This dynamic created what behavioral scientists call the <b>Outrage Feedback Loop</b>: platforms optimize their recommendation "
        "algorithms for emotional arousal (specifically moral outrage, anxiety, and tribal fear), publishers adapt their editorial output "
        "to satisfy these algorithms, and readers become chronically hyper-stimulated yet profoundly uninformed.",
        styles['Body']
    ))
    
    story.extend(add_callout(
        "The Core Economic Perversion of Ad-Tech",
        "Engagement = Total Time on Screen × Emotional Volatility.<br/>"
        "Under this economic model, calm nuance is not merely unprofitable — it is actively suppressed by recommendation algorithms "
        "because it allows the human mind to pause, reflect, and look away.",
        styles,
        kind="warning"
    ))
    
    story.append(Paragraph("<b>1.2 The Death of Context: The 280-Character Soundbite</b>", styles['H2']))
    story.append(Paragraph(
        "Simultaneously, the modern consumption layer degraded the depth of reporting. Platforms like X (formerly Twitter) trained "
        "an entire generation of citizens to consume complex geopolitical, economic, and technological developments in 280-character soundbites. "
        "Context — the historical background, institutional nuances, counter-arguments, and statistical realities — was systematically stripped away.",
        styles['Body']
    ))
    story.append(Paragraph(
        "When context is removed, every news event appears unprecedented, catastrophic, or treasonous. Public discourse fractures into "
        "hostile tribal camps arguing over decontextualized snippets rather than substantive policy. "
        "The citizen is kept in a permanent state of emergency, jumping from one manufactured crisis to the next without ever gaining "
        "the systematic comprehension required for genuine civic participation.",
        styles['Body']
    ))
    
    story.append(Paragraph("<b>1.3 Ad-Tech Parasitism: The Visual Assault of the Web</b>", styles['H2']))
    story.append(Paragraph(
        "Even when a motivated reader seeks out long-form reporting on mainstream news portals, the browser experience has become "
        "unusable. Let us conduct an honest technical audit of what occurs when a user visits a mainstream news website in 2026:",
        styles['Body']
    ))
    
    assault_points = [
        ("The Cookie Consent Overlay", "A massive modal dialogue demanding immediate compliance choices before the page renders, using dark patterns to trick users into accepting tracking beacons."),
        ("The Newsletter Interstitial", "A full-screen modal interrupting the reading flow within three seconds: 'Join 500,000 smart readers! Enter your email now.'"),
        ("The Sticky Video Player", "An auto-playing video ad that pins itself to the bottom-right corner of the viewport, consuming mobile battery, CPU cycles, and cellular data."),
        ("Third-Party Tracking Beacons", "Dozens of programmatic tracking pixels (Google Ad Manager, Criteo, Taboola, Outbrain, Facebook Pixel) executing hundreds of HTTP requests, inflating page weight from 500kB to 14MB."),
        ("Layout Jitter & Reflow", "As asynchronous banner advertisements load at variable speeds, the text block jumps up and down unpredictably, causing users to lose their reading place."),
        ("Deceptive Churn Grids", "At the base of the article, a grid of sponsored clickbait headlines ('Doctors in shock! One simple trick to burn belly fat') designed to look like editorial recommendations.")
    ]
    for title, desc in assault_points:
        story.append(Paragraph(f"• <b>{title}:</b> {desc}", styles['Bullet']))
        
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "This is not journalism; this is commercial parasitism. The reader's cognitive bandwidth is treated as an open quarry to be mined. "
        "Keywords News was built on the premise that readers deserve better.",
        styles['Body']
    ))
    
    story.append(Paragraph("<b>1.4 Comparative Performance Audit: Mainstream News vs. Keywords News</b>", styles['H2']))
    story.append(Paragraph(
        "To quantify the staggering difference between the commercial web and our clean architecture, we benchmarked an identical article "
        "loaded on a mainstream Indian news portal versus within Keywords News Reader Mode:",
        styles['Body']
    ))
    
    audit_table = [
        ["Metric / Diagnostic", "Mainstream News Portal", "Keywords News Reader Mode", "Advantage"],
        ["Page Weight (Data Transferred)", "12.4 MB (Scripts, ads, trackers)", "184 KB (Clean HTML + Font)", "98.5% Reduction"],
        ["Total HTTP Network Requests", "186 requests (ad servers, pixels)", "2 requests (Edge Proxy + Text)", "98.9% Fewer Requests"],
        ["Time to Interactive (TTI)", "8.2 seconds (heavy scripting)", "0.38 seconds (instant DOM)", "21x Faster"],
        ["Third-Party Trackers & Beacons", "42 external tracking cookies", "0 trackers (Completely Private)", "100% Private"],
        ["Layout Cumulative Shift (CLS)", "0.48 (Jumping ads & popups)", "0.00 (Zero layout shift)", "Flawless Stability"]
    ]
    story.extend(add_table(audit_table[0], audit_table[1:], [130, 130, 130, 114], styles))
    story.append(PageBreak())

    # =========================================================================
    # CHAPTER 2: THE CORE PRODUCT PHILOSOPHY
    # =========================================================================
    story.append(ChapterMarker("ch2"))
    story.append(Paragraph("Chapter 2: The Core Product Philosophy & The Five Sacred Tenets", styles['ChapterTitle']))
    story.append(HRFlowable(width="100%", thickness=1, color=SECONDARY, spaceAfter=14, spaceBefore=4))
    
    story.append(Paragraph(
        "Keywords News was conceived not merely as an alternative software application, but as a philosophical manifesto rendered in code. "
        "To protect the platform against the creeping corruption that infects other media products, the founder established "
        "<b>Five Sacred Tenets</b>. These tenets are hard-coded into our architecture, data structures, and algorithms:",
        styles['Body']
    ))
    
    story.append(Paragraph("<b>2.1 Tenet 1: Zero Algorithmic Dopamine</b>", styles['H2']))
    story.append(Paragraph(
        "The platform explicitly rejects engagement-maximizing algorithms. There is no 'For You' page generated by opaque neural networks "
        "hunting for your psychological weaknesses. Content is organized strictly into discrete, intentional topic verticals (UPSC & Governance, "
        "Tech & Design, Men's Style, Running, Automotive, Photography). The user chooses what they want to study; they read what is present; "
        "and when the session is complete, they close the app informed and unburdened. We do not design for addiction; we design for departure.",
        styles['Body']
    ))
    story.append(Paragraph(
        "In traditional social media apps, the infinite scroll creates a psychological slot machine: every swipe might reveal a prize or a outrage. "
        "In Keywords News, feeds have clear boundaries. Articles are chronologically balanced and curated. When you reach the bottom of the feed, "
        "you have completed your reading. There is no synthetic dopamine loop keeping you trapped.",
        styles['Body']
    ))
    
    story.append(Paragraph("<b>2.2 Tenet 2: The 70/30 Regional Balancing Equation</b>", styles['H2']))
    story.append(Paragraph(
        "A major hazard of modern internet news aggregation is geographic alienation. High-volume international tech blogs produce thousands "
        "of articles on Silicon Valley startups, Western celebrity culture, and US domestic politics. Without explicit structural intervention, "
        "an Indian reader's newsfeed quickly becomes detached from their national reality.",
        styles['Body']
    ))
    story.append(Paragraph(
        "Keywords News hard-codes the <b>70/30 Regional Balance Equation</b>: exactly 70% of the primary feed is composed of Indian national, "
        "economic, public policy, and regional journalism, while 30% brings essential global international perspective. "
        "This guarantees that the reader stays deeply grounded in Indian civic life while maintaining an expansive global worldview.",
        styles['Body']
    ))
    
    story.append(Paragraph("<b>2.3 Tenet 3: Anti-Monopoly Round-Robin Source Diversity</b>", styles['H2']))
    story.append(Paragraph(
        "In raw RSS syndication, volume does not equal quality. Mainstream wire services publish upwards of 50 short bulletins per hour, "
        "whereas specialized, high-depth publications (such as The Hindu, Livemint, or MIT Technology Review) publish 5 thoughtful articles a day. "
        "If an aggregator simply sorts by chronological timestamp, the wire services completely monopolize the reader's view.",
        styles['Body']
    ))
    story.append(Paragraph(
        "Our <b>Round-Robin Interleaving Algorithm</b> solves this by grouping incoming articles by publication and drawing them in strict "
        "rotational sequence. No single media house is ever permitted to dominate the feed, ensuring a rich symphony of editorial viewpoints.",
        styles['Body']
    ))
    
    story.append(Paragraph("<b>2.4 Tenet 4: Clean In-App Reader: The Web Stripped of Greed</b>", styles['H2']))
    story.append(Paragraph(
        "Clicking a headline in Keywords News does not throw the user out into the hostile ad-tech jungle. Instead, our in-app Reader Mode "
        "retrieves the raw article HTML and processes it through a customized implementation of Mozilla Readability. "
        "Every banner ad, tracking beacon, full-page modal, and promotional carousel is annihilated. What remains is pure, serene text "
        "typeset in beautiful serif typography (Lora and Playfair Display), with dark and light modes tailored for optical comfort.",
        styles['Body']
    ))
    
    story.append(Paragraph("<b>2.5 Tenet 5: Cognitive AI: Augmentation, Not Hallucination</b>", styles['H2']))
    story.append(Paragraph(
        "Keywords News rejects the modern obsession with generating synthetic, AI-generated news. Synthetic journalism is prone to hallucination, "
        "erodes editorial accountability, and pollutes the historical record.",
        styles['Body']
    ))
    story.append(Paragraph(
        "In Keywords News, Artificial Intelligence is deployed exclusively as an intellectual assistant to the human mind: providing concise "
        "2-3 sentence executive summaries of long-form articles, and powering the floating <b>AI Concept Explainer</b>, which defines complex "
        "jargon (e.g. 'Current Account Deficit', 'Zero-Knowledge Proofs') in two clear, accessible sentences upon user selection.",
        styles['Body']
    ))
    
    story.extend(add_callout(
        "Architectural Mandate for Future Maintainers",
        "If you are an engineer modifying this codebase in the future, these Five Tenets are non-negotiable. "
        "Do not introduce addictive engagement mechanics. Do not weaken the 70/30 ratio. "
        "Do not allow wire services to monopolize the feed. Protect the sanctity of the reading experience above all else.",
        styles,
        kind="info"
    ))
    story.append(PageBreak())
    
    return story
